stages:
  - test
  - build
  - integration
  - release

Unit Test:
  image: golang:1.12-alpine
  stage: test
  only:
    - develop
  tags:
    - docker-builder
  script:
    - go test ./...

Build:
  image: golang:1.12-alpine
  stage: build
  only:
    - master
  tags:
    - docker-builder
  before_script:
    - apk add --no-cache tzdata
    - cp /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
  script:
    - ./scripts/build.sh
  artifacts:
    expire_in: 30 mins
    paths:
      - binaries/enable

PHP 7.2 Test:
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-7.2
  stage: integration
  dependencies:
    - Build
  only:
    - master
  tags:
    - docker-builder
  script:
    - binaries/enable -a

PHP 7.3 Test:
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-7.3
  stage: integration
  dependencies:
    - Build
  only:
    - master
  tags:
    - docker-builder
  script:
    - binaries/enable -a

PHP 5.6 Test:
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-5.6
  stage: integration
  dependencies:
    - Build
  only:
    - master
  tags:
    - docker-builder
  script:
    - binaries/enable -a
