stages:
  - test
  - build
  - integration
  - release

Unit Test:
  image: golang:1.12-alpine
  stage: test
  only:
    - master
  tags:
    - docker-builder
  script:
    - go test ./... --cover

Build Binary:
  image: golang:1.12-alpine
  stage: build
  only:
    - master
  tags:
    - docker-builder
  before_script:
    - apk add --no-cache tzdata
    - cp /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
  script:
    - ./scripts/build.sh
  artifacts:
    expire_in: 30 mins
    paths:
      - bin/enable

.integration_template: &integration
  stage: integration
  dependencies:
    - Build Binary
  only:
    - master
  tags:
    - docker-builder
  script:
    - bin/enable -a


PHP 7.2 Test:
  <<: *integration
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-7.2

PHP 7.3 Test:
  <<: *integration
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-7.3

PHP 5.6 Test:
  <<: *integration
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-5.6

Build Image:
  image: gitlab.vygr.net:5005/dev/docker/ci
  stage: release
  dependencies:
    - Build Binary
  only:
    - master
  tags:
    - docker-builder
  before_script:
    - docker_ci login
  script:
    - docker build --file Dockerfile --tag ${CI_REGISTRY_IMAGE} bin
    - docker push ${CI_REGISTRY_IMAGE}
  after_script:
    - docker_ci logout
