stages:
  - test
  - integration
  - release

Unit Test:
  image: golang:1.12-alpine
  stage: test
  only:
    - master
  tags:
    - docker-builder
  script:
    - go test ./...

Build Binary:
  image: golang:1.12-alpine
  stage: test
  only:
    - master
  tags:
    - docker-builder
  before_script:
    - apk add --no-cache tzdata
    - cp /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
  script:
    - ./scripts/build.sh
  artifacts:
    expire_in: 30 mins
    paths:
      - binaries/enable

PHP 7.2 Test:
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-7.2
  stage: integration
  dependencies:
    - Build Binary
  only:
    - master
  tags:
    - docker-builder
  script:
    - binaries/enable -a

PHP 7.3 Test:
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-7.3
  stage: integration
  dependencies:
    - Build
  only:
    - master
  tags:
    - docker-builder
  script:
    - binaries/enable -a

PHP 5.6 Test:
  image: gitlab.vygr.net:5005/dev/docker/alpine/php-5.6
  stage: integration
  dependencies:
    - Build
  only:
    - master
  tags:
    - docker-builder
  script:
    - binaries/enable -a

Build Image:
  image: gitlab.vygr.net:5005/dev/docker/ci
  stage: release
  only:
    - master
  tags:
    - docker-builder
  before_script:
    - docker_ci login
  script:
    - docker build --file Dockerfile --tag ${CI_REGISTRY_IMAGE} binaries
    - docker push ${CI_REGISTRY_IMAGE}
  after_script:
    - docker_ci logout
