stages:
  - build
  - release

Build Binary:
  image: golang:1.11-alpine
  stage: build
  only:
    - tags
  tags:
    - docker-builder # no need for docker but currently lacks a generic build runner
  before_script:
    - apk add --no-cache tzdata
    - cp /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
  script:
    - go test
    - ./build.sh
  artifacts:
    expire_in: 10 mins
    paths:
      - binaries/enable

Build Image:
  image: docker
  stage: release
  only:
    - tags
  tags:
    - docker-builder
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - base=${CI_REGISTRY_IMAGE}
    - tag=${base}:${CI_COMMIT_TAG}
    - docker build --file Dockerfile --tag ${tag} binaries
    - docker tag ${tag} ${base}
    - docker push ${tag}
    - docker push ${base}
  after_script:
    - docker logout $CI_REGISTRY
